apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
  labels:
    app: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: kopiadjie/testdev:0.1
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-devops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---

apiVersion: v1
kind: Service
metadata:
  name: dev-service
spec:
  type: NodePort
  selector:
    app: devops
  ports:
    - port: 8000

      targetPort: 8000

      nodePort: 30007